a = float (input ("podaj liczbe a:"))
b = float (input ("podaj liczbe b:"))
z_dod = round(a+b, 1)
print ("suma:", z_dod)
z_od = round(a-b, 1)
print ("różnica:", z_od)
z_mno = round(a*b, 1)
print ("iloczyn:", z_mno)
z_dzi = round(a/b, 1)
print ("iloraz:", z_dzi)
